apiVersion: v1
kind: Pod
metadata:
  name: my-grpc-server
  labels:
    app: backend-grpc
spec:
  containers:
    - name: my-grpc-server-containers
      image: docker.io/pontryaginmaxim/chat-server:v2
      ports:
        - containerPort: 50061
      resources:
        limits:
          memory: "128Mi"
          cpu: "50m"